FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y --force-yes wget ruby ruby-dev

RUN gem install bundle --no-ri --no-rdoc

COPY Gemfile Gemfile
RUN bundle install

RUN wget -L https://github.com/aelsabbahy/goss/releases/download/v0.0.16/goss-linux-amd64 > /usr/local/bin/goss && chmod +x /usr/local/bin/goss
RUN wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.5.1-1_amd64.deb
RUN dpkg -i chef_12.5.1-1_amd64.deb

